name: Request Copilot PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  request-copilot-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Request GitHub Copilot review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            
            // Request review from GitHub Copilot
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              reviewers: ['copilot']
            });
            
            console.log(`Requested GitHub Copilot review for PR #${prNumber}`);
